from datagenerators.generator import DataGenerator
from datagenerators.generate_var import VARGenerator
from datagenerators.generate_ngc_var import NGCVARGenerator
from datagenerators.generate_svm import SVMGenerator
from datagenerators.generate_stock_data import StockGenerator